### ISSUE TITLE
[Запрос] Нужен готовый FlyDirt.jar

### ISSUE THREAD

**Issue by PC-Leonid-PC** [PC-Leonid-PC/FlyDirt-Paper#1]
@Leonid_Bro привет!  
Пожалуйста, загрузи готовый `.jar` файл плагина со следующими параметрами:
- Версия: Paper 1.12.2
- Функция: `/flydirt` для невидимости + летающий блок земли
- Оптимизация: для серверов с TPS > 18

Дополнительно:
- [ ] Нужна проверка SHA-256
- [ ] Готов протестировать и дать фидбек

Спасибо!

**Comment by PC-Leonid-PC** [comment]
**Полный код плагина (для сборки):**  

1. `plugin.yml`:  
```yaml
name: FlyDirt-Paper
main: me.leonid.flydirt.FlyDirtPlugin
version: 1.0
api-version: 1.12
commands:
  flydirt:
    description: "Делает игрока невидимым с блоком земли"
```

2. Класс `FlyDirtPlugin.java`:  
```java
// Вставь код из моих предыдущих сообщений (или напиши мне — скину ещё раз)
```

**Инструкция:**  
- Скомпилируй через `javac -cp paper-api-1.12.2.jar FlyDirtPlugin.java`  
- Собери JAR: `jar cvf FlyDirt.jar plugin.yml me/leonid/flydirt/*.class`
